name: smart_ar_navigation
description: "Smart AR Navigation App for Enhanced Driving Assistance"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies: 
  flutter: 
    sdk: flutter

  cupertino_icons: ^1.0.8

  # AR
  ar_flutter_plugin_2: ^0.0.3 

  # Google Maps & Navigation
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.0

  # GPS Location
  geolocator: ^12.0.0 

  # HTTP requests to Google APIs
  http: ^1.1.0

  # State Management
  provider: ^6.1.0

  # API Key management
  flutter_dotenv: ^5.1.0

dev_dependencies: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/